In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/NFWBS_PUF_2016_data.csv")

In [3]:
columns_of_interest = [
    'PUF_ID',
    'PPREG4',
    'PPREG9',
    'PPGENDER',
    'agecat',
    'PPETHM',
    'PPEDUC',
    'PPINCIMP',
    'PPHHSIZE',
    'FWB1_5',
    'AUTOMATED_1',
    'HOUSING',
    'KIDS_NoChildren',
    'KIDS_1',
    'KIDS_2',
    'KIDS_3',
    'KIDS_4',
    'EMPLOY',
    'ENDSMEET',
    'FWB1_1',
    'ACT1_2',
    'PRODHAVE_8',
    'PRODUSE_2',
    'PPMARIT',
    'HHEDUC',
    'PAREDUC',
    'HOUSESAT',
    'SWB_1',
    'MANAGE1_2',
    'AUTOMATED_2'
]

In [4]:
filtered_df = df.loc[:,columns_of_interest]
filtered_df.head()

,PUF_ID,PPREG4,PPREG9,PPGENDER,agecat,PPETHM,PPEDUC,PPINCIMP,PPHHSIZE,FWB1_5,...,ACT1_2,PRODHAVE_8,PRODUSE_2,PPMARIT,HHEDUC,PAREDUC,HOUSESAT,SWB_1,MANAGE1_2,AUTOMATED_2
0,10350,4,8,1,8,1,4,7,1,2,...,3,0,0,3,4,4,4,5,4,0
1,7740,2,3,1,3,1,2,6,2,3,...,3,0,0,3,2,2,3,6,4,0
2,13699,4,9,1,3,2,3,6,3,3,...,3,0,0,3,3,3,3,4,3,1
3,7267,3,7,1,3,1,2,8,1,3,...,-1,0,0,3,-1,2,-1,6,4,-1
4,7375,2,4,1,2,3,2,7,5,3,...,3,0,1,1,2,2,3,4,3,1

In [5]:
filtered_df.to_csv(r'cfpb_combined_prep.csv', index = False)

In [6]:
col_map = {
    'PPREG4':'Census Region',
    'PPREG9':'Census Division',
    'PPGENDER':'Gender',
    'agecat':'Age Group',
    'PPETHM':'Race/Ethnicity',
    'PPEDUC':'Education (Highest Degree)',
    'PPINCIMP':'Household Income',
    'PPHHSIZE':'Household Size',
    'FWB1_5':'I am just getting by financially',
    'AUTOMATED_1':'A Retirement Savings Account',
    'HOUSING':'Which one of the following best describes your housing situation?',
    'KIDS_NoChildren':'I have no children that I support financially',
    'KIDS_1':'Less than 7 years old',
    'KIDS_2':'7 to 12 years old',
    'KIDS_3':'13 to 17 years old',
    'KIDS_4':'More than 18 years old',
    'EMPLOY':'Primary or only employment status',
    'ENDSMEET':'Difficulty of covering monthly expenses and bills',
    'FWB1_1':'I could handle a major unexpected expense.',
    'ACT1_2':'I follow-through on financial goals I set for myself.',
    'PRODHAVE_8':'Student/Education Loan (for yourself or someone else)',
    'PRODUSE_2':'Used pawn loan or auto title loan',
    'PPMARIT':'Marital Status',
    'HHEDUC':'Highest level of education of all household members',
    'PAREDUC':'Highest level of education by person/people who raised respondent',
    'HOUSESAT':'How satisfied are you with the place you live currently?',
    'SWB_1':'I am satisfied with my life',
    'MANAGE1_2':'Stayed within your budget or spending plan',
    'AUTOMATED_2':'A Non-Retirement Savings Account',
}